services:
  - type: web
    name: blazes
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CONTACT_EMAIL_USER
        sync: false
      - key: CONTACT_EMAIL_PASS
        sync: false
